replicaCount: 1

image:
  repository: harshjswl/todo-devops
  tag: v1
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30018

namespace: todo-dev

resources: {}
db:
  url: jdbc:postgresql://todo-postgres.cl6y8uko4auc.ap-south-1.rds.amazonaws.com:5432/tododb
  username: postgres
  password: Devops12345

















