replicaCount: 1

image:
  repository: harshjswl/todo-devops
  tag: v1
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30018

resources: {}

namespace: todo-dev
